### ISSUE TITLE
Longer GIF previews don't loop correctly

### ISSUE THREAD

**Issue by dlsf** [voidnyan/void-verified#145]
**Describe the bug**
When you use a longer GIF for a layout preview (such as [this](https://s4.anilist.co/file/anilistcdn/user/avatar/large/b5547292-TbCvA7hg1Lg1.gif) one), it only seems to loop for about a second.

**To Reproduce**
1. Create a new layout
2. Use a long GIF as an avatar
3. Click "Enable Preview"
4. Navigate to your profile

**Expected behavior**
The GIF should be displayed exactly as if it were applied properly.

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version: 1.12.0

**Comment by voidnyan** [comment]
thanks for the bug report! the fix will be published in the next version.
